version: '3.2'

services:
  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411

  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: Frontend
    depends_on:
      - "kafka-zookeeper"

  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: Backend
    depends_on:
      - "kafka-zookeeper"

  kafka-zookeeper:
    image: openzipkin/zipkin-kafka
    container_name: kafka-zookeeper
    # If using docker machine, uncomment the below and set your bootstrap
    # server list to 192.168.99.100:19092
    # environment:
      # - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
    ports:
      - 2181:2181
      - 9092:9092
      # port 19092 is listening on localhost by default. In normal Docker,
      # you can set your bootstrap server list to localhost:19092
      - 19092:19092
